[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer_runs = 200
libs = ["lib"]

[fmt]
line_length = 80
multiline_func_header = 'all'
number_underscore = 'thousands'
wrap_comments = true